name: fixit_core
description: Core logging, versioning, and event bus utility package for Fixit Runtime SDK.
version: 1.0.0
publish_to: none

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  meta: ^1.9.0
