name: fixit_core
# Developed by Fixitbhaii Solutions for production grade applications
description: Core logging, versioning, and event bus utility package for the Fixit Runtime SDK.
version: 1.0.1
repository: https://github.com/Greatversion/fixit_core
issue_tracker: https://github.com/Greatversion/fixit_core/issues
topics:
  - logging
  - event-bus
  - utilities

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  meta: ^1.9.0
